[versions]
gradle_android_plugin_version = "8.0.2"
gradle_version = "8.2.1"
kotlin_version = "1.8.22"
ksp_version = "1.8.22-1.0.11"

shadow = "8.1.1"

coroutines = "1.7.3"
androidx_compose_kotlin_compiler = "1.4.8"
desugar_jdk_libs = "2.0.3"

retrofit2 = "2.9.0"
retrofit2_kotlinx_serialization_json = "1.0.0"
kotlinx_serialization_json = "1.5.0"

androidx_annotation = "1.6.0"
androidx_compose_bom = "2023.06.01"
androidx_core = "1.10.1"
androidx_activity = "1.7.2"
androidx_fragment = "1.6.0"
androidx_navigation = "2.6.0"
androidx_lifecycle = "2.6.1"
androidx_appcompat = "1.6.1"
androidx_paging_compose = "3.2.0-beta01"
androidx_constraint_layout_compose = "1.0.1"
androidx_hilt = "2.47"
androidx_hilt_navigation_compose = "1.0.0"
androidx_hilt_navigation_fragment = "1.0.0"
material = "1.9.0"
constraintlayout = "2.1.4"

lottie = "6.0.0"
kotlin_poet = "1.14.2"
google_auto_service = "1.0.1"
google_auto_service_annotation = "1.0.1"
google_auto_common = "1.2.1"

ktlint = "0.49.1"
ktlint_gradle_plugin = "11.4.0"
detekt = "1.23.0"

compile_sdk = "33"
target_sdk = "33"
min_sdk = "26"

lib_compile_sdk = "33"
lib_min_sdk = "23"

nexus_publish_plugin = "1.3.0"
dokka = "1.8.20"
jsoup = "1.16.1"

smart_deeplink_core = "1.0.0-rc06"
smart_deeplink_annotation = "1.0.0-rc05"
simple_dialog = "1.0.1"

[libraries]

androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidx_compose_bom" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material3-windowSizeClass = { group = "androidx.compose.material3", name = "material3-window-size-class" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout" }

androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx_activity" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidx_lifecycle" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidx_navigation" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx_lifecycle" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidx_hilt_navigation_compose" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "androidx_constraint_layout_compose" }

androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "androidx_navigation" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "androidx_navigation" }

androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx_appcompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx_core" }
androidx-fragment = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidx_fragment" }
androidx-activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidx_activity" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx_lifecycle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidx_lifecycle" }
androidx-lifecycle-viewmodel-savedstate = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version.ref = "androidx_lifecycle" }
androidx-lifecycle-compilerkapt = { group = "androidx.lifecycle", name = "lifecycle-compiler", version.ref = "androidx_lifecycle" }

androidx-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "androidx_hilt" }
androidx-hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "androidx_hilt" }
androidx-hilt-navigation-fragment = { group = "androidx.hilt", name = "hilt-navigation-fragment", version.ref = "androidx_hilt_navigation_fragment" }

androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx_annotation" }

desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin_version" }
kotlinx-coroutine = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutine-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx_serialization_json" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit2" }
retrofit-scalars = { group = "com.squareup.retrofit2", name = "converter-scalars", version.ref = "retrofit2" }
retrofit-kotlinx-serialization = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "retrofit2_kotlinx_serialization_json" }

material = { module = "com.google.android.material:material", version.ref = "material" }
kotlin-poet = { module = "com.squareup:kotlinpoet", version.ref = "kotlin_poet" }
kotlin-reflection = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin_version" }
google-autocommon = { module = "com.google.auto:auto-common", version.ref = "google_auto_common" }
google-autoservice-core = { module = "com.google.auto.service:auto-service", version.ref = "google_auto_service" }
google-autoservice-annotation = { module = "com.google.auto.service:auto-service-annotations", version.ref = "google_auto_service_annotation" }
ktlint = { module = "com.pinterest:ktlint", version.ref = "ktlint" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }

smartdeeplink-core = { module = "io.github.pknujsp:smartdeeplink-core", version.ref = "smart_deeplink_core" }
smartdeeplink-annotation = { module = "io.github.pknujsp:smartdeeplink-annotation", version.ref = "smart_deeplink_annotation" }
simpledialog = { module = "io.github.pknujsp:simpledialog", version.ref = "simple_dialog" }

android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "gradle_android_plugin_version" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin_version" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp_version" }

[bundles]
hilt = ["androidx-hilt-android", "androidx-hilt-navigation-fragment"]
compose-hilt = ["androidx-hilt-navigation-compose", ]

compose-debug = ["androidx-compose-ui-tooling"]

compose-core = [
  "androidx-compose-runtime",
  "androidx-compose-ui-util",
  "androidx-compose-ui",
  "androidx-compose-ui-tooling-preview",
  "androidx-compose-foundation",
  "androidx-compose-foundation-layout",
  "androidx-compose-material3", "androidx-constraintlayout-compose", "androidx-compose-material3-windowSizeClass",
]

viewmodel = ["androidx-lifecycle-viewmodel-ktx",
  "androidx-lifecycle-viewmodel-savedstate"]
compose-viewmodel = ["androidx-lifecycle-viewmodel-compose", ]

runtime = ["androidx-lifecycle-runtime-ktx", ]
compose-runtime = ["androidx-lifecycle-runtime-compose"]

navigation = ["androidx-navigation-fragment-ktx", "androidx-navigation-ui-ktx"]
compose-navigation = ["androidx-navigation-compose", ]

activity = ["androidx-activity"]
compose-activity = ["androidx-activity-compose"]

appcompat = ["androidx-appcompat"]

fragment = ["androidx-fragment"]

kotlinx = ["kotlinx-coroutine", "kotlinx-coroutine-core", "kotlinx_serialization_json"]

retrofit = ["retrofit-core", "retrofit-scalars", "retrofit-kotlinx-serialization"]

[plugins]
android-application = { id = "com.android.application", version.ref = "gradle_android_plugin_version" }
android-library = { id = "com.android.library", version.ref = "gradle_android_plugin_version" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin_version" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin_version" }
nav-safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "androidx_navigation" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin_version" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus_publish_plugin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "androidx_hilt" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint_gradle_plugin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin_version" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp_version" }
